export { default as Trash } from './Trash'
export { default as User } from './User'
export { default as Cart } from './Cart'
export { default as Minus } from './Minus'
export { default as Plus } from './Plus'
export { default as Ghost } from './Ghost'
export { default as Bomb } from './Bomb'
export { default as Genius } from './Genius'
export { default as Loading } from './Loading'
export { default as Snake } from './Snake'
export { default as Confuse } from './Confuse'
export { default as Burguer } from './Burguer'
export { default as FiringHeart } from './FiringHeart'
export { default as Heart } from './Heart'
export { default as Demon } from './Demon'
export { default as MagnifiyngGlass } from './MagnifiyngGlass'
export { default as Kettle } from './Kettle'
export { default as WineGlass } from './WineGlass'
export { default as BoxJuice } from './BoxJuice'
export { default as Baloon } from './Baloon'
export { default as OpenBoxJuice } from './OpenBoxJuice'
export { default as Champagne } from './Champagne'
export { default as Fire } from './Fire'
export { default as GlassWater } from './GlassWater'
export { default as CauliFlower } from './CauliFlower'

export interface IconProps {
  classes?: string
}
